### ISSUE TITLE
 Cannot find module 'setupDevtools' from 'setup.js'

### ISSUE THREAD

**Issue by SupriyaKalghatgi** [expo/jest-expo#14]
`package.json`
```
"devDependencies": {
    "jest": "^20.0.4",
    "jest-cli": "^20.0.4",
    "jest-expo": "^19.0.5"
  },
"jest": {
    "verbose": true,
    "preset": "jest-expo",
    "modulePathIgnorePatterns": ["react", "react-native"]
  },
"dependencies": {
    "expo": "19.0.0",
}
```

expo sdkVersion: 19.0.0

Why is that, this error appears again and again

**Comment by larsonjj** [comment]
Hey @SupriyaKalghatgi,

Try adding the following to your jest config within `package.json`:

```
"moduleFileExtensions": ["js", "jsx"]
```

**Comment by LRNZ09** [comment]
Strangely I've resolved by doing:

`yarn test` will initially fail with `Cannot find module 'setupDevtools' from 'setup.js'` error.
`yarn test --no-cache` will fail with the same error.
`yarn test --no-watchman` will fail again.
`yarn test` will pass.

Don't know why but it works now.
Related issue here: https://github.com/expo/jest-expo/issues/14

**Comment by dikaiosune** [comment]
Hi! We're moving all issues to https://github.com/expo/expo. Please reopen there if you're still having issues. Thanks!
