### ISSUE TITLE
Some valid file formats for fonts aren't stubbed (.otf, .woff, .eot)

### ISSUE THREAD

**Issue by cycleseven** [expo/jest-expo#20]
Only `.ttf` seems to be stubbed. This means that an `.otf` import in my Create React Native App project breaks my test suite, unless I override the `moduleNameMapper` setting myself.

https://github.com/expo/jest-expo/blob/master/jest-preset.json#L19

Are non-TTF extensions intentionally left out, or should they be added? Happy to submit a PR if it's the latter!

**Comment by ide** [comment]
This wasn’t intentional but OTF files don’t work consistently so we use TTFs and never ran into a need to mock them. Would take a PR for this.

**Comment by cycleseven** [comment]
@ide Here's a PR that adds otf to the stubbed file formats list. Sorry it took a while to get around to such a small change! https://github.com/expo/jest-expo/pull/22

I didn't come across an issue using otf in my React Native projects so far, would be curious to know what can go wrong. The iOS and Android docs surprisingly don't seem to say too much about supported font formats from what I could find 😞
