### ISSUE TITLE
Running test script fails -- "Cannot find Jest"

### ISSUE THREAD

**Issue by saoirse-zee** [expo/jest-expo#21]
Running `yarn test` results in `Error: Cannot find module '<path-to-project>/node_modules/jest/bin/jest.js'`

This used to work just fine. For some reason, now `node_modules/jest` does not exist. Just to make sure, I ran`rm -rf node_modules && yarn install`. The issue remains.

I feel like I must be doing something dumb because I don't see anyone else reporting this issue. Any help is most appreciated!

Here is my package.json:

```
{
  "main": "node_modules/expo/AppEntry.js",
  "private": true,
  "scripts": {
    "test": "node ./node_modules/jest/bin/jest.js",
    "test-watch": "node ./node_modules/jest/bin/jest.js --watchAll",
    "lint": "eslint src/"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/samples": "2.1.1",
    "axios": "^0.17.1",
    "expo": "^23.0.0",
    "luxon": "^0.0.19",
    "react": "16.0.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-23.0.0.tar.gz",
    "react-navigation": "^1.0.0-beta.19",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0"
  },
  "devDependencies": {
    "babel-eslint": "^8.0.2",
    "eslint": "^4.11.0",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-plugin-compat": "^2.1.0",
    "eslint-plugin-flowtype": "^2.39.1",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-jsx-a11y": "^6.0.2",
    "eslint-plugin-react": "^7.4.0",
    "jest-expo": "^23.0.0"
  }
}
```

**Comment by ide** [comment]
I think there might be something wrong with your computer. I made an empty folder with your package.json and installed deps with both npm and yarn and both of them installed `node_modules/jest`.

**Comment by saoirse-zee** [comment]
@ide Thank you for taking the time to check this out. I think you're right. There must have been something wrong with my local setup. I recreated the project from `package.json` and it worked just fine.
